export enum ChordProgressionType {
  Perfect_Cadence = "Perfect Cadence",
  Plagal_Cadence = "Plagal Cadence",
  Line_Cliche = "Line Cliche",
  Gypsy_Woman = "Gypsy Woman",
  Around_The_World = "Around The World (Lalalalala)",
  LetItBe = "Let It Be",
  LetItBe_Intermission = "Let It Be (Intermission)",
  WithOrWithoutYou = "With or Without You",
  Something = "Something (Beatles)",
  Blues = "Blues Progression",
  Creep = "Creep (Radiohead)",
  The_World_Is_Not_Enough = "The World Is Not Enough (Garbage)",
  All_I_Want_For_Christmas = "All I Want for Christmas",
  Careless_Whisper = "Careless Whisper",
  Michelle = "Michelle (Beatles)",
  Bohemian_Rhapsody_Mama = "Bohemian Rhapsody (Mama)",
}
