export enum ChordProgressionType {
  Plagal_Cadence = "Plagal Cadence",
  Perfect_Cadence = "Perfect Cadence",
  Line_Cliche = "Line Cliche",
  Fifties_Progression = "50s Progression",
  Two_Five_One = "2-5-1",
  Andalusian_Cadence = "Andalusian Cadence",
  Gypsy_Woman = "Gypsy Woman",
  Around_The_World = "Around The World (Lalalalala)",
  LetItBe = "Let It Be",
  LetItBe_Intermission = "Let It Be (Intermission)",
  WithOrWithoutYou = "With or Without You",
  Something = "Something (Beatles)",
  Creep = "Creep (Radiohead)",
  The_World_Is_Not_Enough = "The World Is Not Enough (Garbage)",
  All_I_Want_For_Christmas = "All I Want for Christmas",
  Careless_Whisper = "Careless Whisper",
  Michelle = "Michelle (Beatles)",
  Bohemian_Rhapsody_Mama = "Bohemian Rhapsody (Mama)",
  Sing_For_Absolution = "Sing for Absolution (Muse)",
}
